model:
  config:
    conv_channels: 64
    dropout: 0.255082136691957
    end_channels: 128
    gcn_depth: 4
    in_dim: 32
    include_static_data: true
    node_dim: 64
    num_layers: 3
    propalpha: 0.1685560057680006
    residual_channels: 16
    subgraph_size: 10
    skip_channels: 32
    tanhalpha: 5.528962634102463

trainer:
  config:
    ema: false
  optimizer:
    lr: 0.0001702892094689578
  # IDK how to do a proper subtree substitution. That's the problem for the future me
  criterion:
    _target_: torch.nn.MSELoss