model:
  config:
    activation: tanh
    include_static_data: True
    input_dim: 4
    max_diffusion_step: 1
    num_rnn_layers: 3
    rnn_units: 64
    use_embedding: True
trainer:
  config:
    ema_decay: 0.9950636293275859
    ema: True
    batch_size: 64
    num_epochs: 50
  optimizer:
    lr: 0.0031505002992112388
  criterion:
    _target_: torch.nn.L1Loss

evaluator:
  config:
    batch_size: 64