hydra:
  sweeper:
    params:
      model.config.max_diffusion_step: choice(1,2)
      model.config.num_rnn_layers: choice(2,3)
      model.config.rnn_units: choice(32,64,128)
      model.config.activation: choice(tanh,relu)
      trainer.config.ema: choice(true, false)
      +trainer.config.ema_decay: interval(0.9,0.9999)
      trainer.optimizer.lr: tag(log,interval(1e-5,1e-2))
      trainer/criterion: choice(L1,MSE)
trainer:
  config:
    batch_size: 64
    num_epochs: 30
evaluator:
  config:
    batch_size: 64
dataset:
  config:
    graph: true