hydra:
  sweeper:
    params:
      model.config.num_layers: choice(1,2,3,4,5)
      model.config.hidden_size: choice(64, 128, 256, 384, 512)
      model.config.embedding_dim: choice(8, 16, 32, 64)
      model.config.dropout: interval(0, 1)
      trainer.optimizer.lr: tag(log, interval(1e-5, 1e-2))
      trainer.config.ema: choice(true, false)
      +trainer.config.ema_decay: interval(0.9, 0.9999)
      trainer.config.batch_size: choice(128)
model:
  config:
    use_embedding: true

trainer:
  config:
    num_epochs: 20
  criterion:
    _target_: torch.nn.L1Loss

dataset:
  config:
    train_samples: 100000
    memory_mapped: True