trainer:
  config:
    ema_decay: 0.9101936248008481
    batch_size: 16384
    ema: True
    num_epochs: 30
  
  optimizer:
    lr: 0.0004632887748560879
  
  criterion:
    _target_: criterion.TweedieLoss
    p: 1.033391495108709

model:
  config:
    activation: ReLU
    pooling_mode: MaxPool1d
    hidden_size: 1024
    n_blocks: [1,2,1]
    n_freq_downsample: [4,2,1]
    n_pool_kernel_size: [4,2,1]
    n_mlp_layers: 4

dataset:
  config:
    memory_mapped: True 
    train_samples: 1000000

evaluator:
  config:
    save_predictions: True
    batch_size: 16384
