model:
  config:
    dropout: 0.09332825894020993
    hidden_size: 192
    n_head: 4
    quantiles: [0.1, 0.5, 0.9]
    output_selector: 1

trainer:
  config:
    ema: True
    ema_decay: 0.9896705542628265
    batch_size: 1024
    num_epochs: 20

  optimizer:
    lr: 0.0025260625827691675

  criterion:
    _target_: criterion.QuantileLoss
    quantiles: [0.1, 0.5, 0.9]

dataset:
  config:
    train_samples: 1000000
    MultiID: False
    binarized: True