# SPDX-License-Identifier: Apache-2.0
_target_: inference.inference_triton.run_inference_triton
config:
    checkpoint: ???
    batch_size: 64
    evaluator:
        _target_: evaluators.triton_evaluator.TritonEvaluator