model:
  config:
    stacks:
        - type: "trend"
          num_blocks: 4
          theta_dim: 2
          share_weights: True
          hidden_size: 2048
        - type: "seasonality"
          num_blocks: 2
          theta_dim: 0
          share_weights: False
          hidden_size: 2048

trainer:
  config:
    batch_size: 16384
    num_epochs: 20
    ema: true
    ema_decay: 0.9463339577642854
  optimizer:
    lr: 0.0002713846381337294