trainer:
  config:
    ema_decay: 0.9453562159037722
    batch_size: 16384
    ema: True
    num_epochs: 30
  
  optimizer:
    lr: 0.000718489072451614
  
  criterion:
    _target_: torch.nn.L1Loss

model:
  config:
    stacks:
        - type: "trend"
          num_blocks: 8
          theta_dim: 16
          share_weights: True
          hidden_size: 256
        - type: "generic"
          num_blocks: 8
          theta_dim: 2
          share_weights: False
          hidden_size: 1024


dataset:
  config:
    memory_mapped: True 
    train_samples: 1000000

evaluator:
  config:
    save_predictions: True
    batch_size: 16384
