model:
  config:
    dropout: 0.04391771729319136
    hidden_size: 256
    n_head: 2
    quantiles: [0.1, 0.5, 0.9]
    output_selector: 1

trainer:
  config:
    ema: True
    ema_decay: 0.9965621619369646
    batch_size: 1024
    num_epochs: 15

  optimizer:
    lr: 0.003036631689885819

  criterion:
    _target_: criterion.QuantileLoss
    quantiles: [0.1, 0.5, 0.9]