trainer:
  config:
    ema_decay: 0.9722933574544365
    batch_size: 16384
    ema: True
    num_epochs: 30
  
  optimizer:
    lr: 3.848204675023239e-05
  
  criterion:
    _target_: criterion.TweedieLoss
    p: 1.8099786820097208

model:
  config:
    activation: Sigmoid
    pooling_mode: MaxPool1d
    hidden_size: 256
    n_blocks: [2,2,2]
    n_freq_downsample: [2,2,1]
    n_pool_kernel_size: [3,3,1]
    n_mlp_layers: 3

dataset:
  config:
    memory_mapped: True 
    train_samples: 1000000

evaluator:
  config:
    save_predictions: True
    batch_size: 16384
