model:
  config:
    activation: tanh
    include_static_data: false
    input_dim: 4
    max_diffusion_step: 1
    num_rnn_layers: 2
    rnn_units: 64
    use_embedding: True
trainer:
  config:
    ema_decay: 0.9950577865524792
    ema: True
    batch_size: 64
    num_epochs: 60
  optimizer:
    lr: 0.001899686550575439
  criterion:
    _target_: torch.nn.L1Loss

evaluator:
  config:
    batch_size: 64