model:
  config:
    stacks:
        - type: "generic"
          num_blocks: 8
          theta_dim: 8
          share_weights: False
          hidden_size: 512
        - type: "generic"
          num_blocks: 4
          theta_dim: 8
          share_weights: True
          hidden_size: 256

trainer:
  config:
    ema: True
    ema_decay: 0.9765061653846568
    batch_size: 16384
    num_epochs: 20

  optimizer:
    lr: 0.00018968004265854346

dataset:
  config:
    train_samples: 1000000
    MultiID: False
    binarized: True