trainer:
  config:
    ema_decay: 0.9412710347501564
    batch_size: 1024
    ema: True
    num_epochs: 20
  
  optimizer:
    lr: 0.0003946489348284673
  
  criterion:
    _target_: criterion.TweedieLoss
    p: 1.1011198699619675

model:
  config:
    dropout: 0.8065306916236111
    hidden_size: 256
    n_head: 1 

dataset:
  config:
    memory_mapped: True 
    train_samples: 1000000

evaluator:
  config:
    save_predictions: True
