# SPDX-License-Identifier: MIT
model:
  config:
    stacks:
        - type: "generic"
          num_blocks: 8
          theta_dim: 2
          share_weights: True
          hidden_size: 2048
        - type: "generic"
          num_blocks: 8
          theta_dim: 2
          share_weights: False
          hidden_size: 1024

trainer:
  config:
    batch_size: 16384
    num_epochs: 20
