# SPDX-License-Identifier: MIT
model:
  config:
    stacks:
        - type: "generic"
          num_blocks: 4
          theta_dim: 8
          share_weights: False
          hidden_size: 1024
        - type: "generic"
          num_blocks: 4
          theta_dim: 8
          share_weights: False
          hidden_size: 2048

trainer:
  config:
    batch_size: 16384
    num_epochs: 20
