model:
  config:
    gcn_depth: 1
    dropout: 0.01757525023094229
    subgraph_size: 10
    node_dim: 128
    conv_channels: 128
    residual_channels: 128
    skip_channels: 128
    end_channels: 128
    num_layers: 2
    propalpha: 0.01950469803970105
    tanhalpha: 4.167126012423724
    in_dim: 16

trainer:
  config:
    num_epochs: 40
    ema: false
    batch_size: 64

  optimizer:
    lr: 0.00029154436869926136

  criterion: 
    _target_: torch.nn.L1Loss