trainer:
  config:
    batch_size: 16384
    ema: False
    num_epochs: 30
  
  optimizer:
    lr: 0.00018694983658104237
  
  criterion:
    _target_: criterion.TweedieLoss
    p: 1.1348446229080165

model:
  config:
    stacks:
        - type: "trend"
          num_blocks: 8
          theta_dim: 2
          share_weights: False
          hidden_size: 2048
        - type: "generic"
          num_blocks: 2
          theta_dim: 0
          share_weights: False
          hidden_size: 2048


dataset:
  config:
    memory_mapped: True 
    train_samples: 1000000

evaluator:
  config:
    save_predictions: True
    batch_size: 16384