hydra:
  sweeper:
    params:
      model.config.num_layers: choice(2,3,4,5)
      model.config.hidden_size: choice(256,512,1024)
      model.config.embedding_dim: choice(16,32,64,128)
      model.config.dropout: interval(0,0.6)
      trainer.optimizer.lr: tag(log, interval(1e-4, 1e-2))
      trainer.config.ema: choice(true, false)
      +trainer.config.ema_decay: interval(0.95, 0.9999)
      +trainer.config.cl_update: choice(300,500,1000,1500)
model:
  config:
    use_embedding: true

trainer:
  config:
    cl_start_horizon: 1
    batch_size: 128
    num_epochs: 7
  criterion:
    _target_: criterion.GaussianLogLikelihood