model:
  config:
    n_head: 4
    hidden_size: 192
    dropout: 0.2662993510864524
    quantiles: [0.1, 0.5, 0.9]
    output_selector: 1

dataset:
  config:
    train_samples: 1000000
    MultiID: False
    binarized: True

trainer:
  config:
    batch_size: 1024
    num_epochs: 15
    ema: true
    ema_decay: 0.9529502308809386

  optimizer:
    lr: 0.001082857288295992

  criterion:
    _target_: criterion.QuantileLoss
    quantiles: [0.1, 0.5, 0.9]