model:
  config:
    dropout: 0.07066822668168525
    hidden_size: 192
    n_head: 2
    quantiles: [0.1, 0.5, 0.9]
    output_selector: 1

trainer:
  config:
    ema: True
    ema_decay: 0.9975301913477509
    batch_size: 1024
    num_epochs: 15

  optimizer:
    lr: 0.001887233159762666

  criterion:
    _target_: criterion.QuantileLoss
    quantiles: [0.1, 0.5, 0.9]