model:
  config:
    n_mlp_layers: 4
    hidden_size: 1024
    activation: ReLU
    pooling_mode: MaxPool1d

    n_blocks: [2,2,2]
    n_pool_kernel_size: [6,3,1]
    n_freq_downsample: [3,3,1]

trainer:
  config:
    ema: True
    ema_decay: 0.941526189213896
    batch_size: 16384
    num_epochs: 35

  optimizer:
    lr: 0.000213020893268614

  criterion:
    _target_: torch.nn.MSELoss

dataset:
  config:
    train_samples: 1000000
    MultiID: False
    binarized: True