# SPDX-License-Identifier: MIT
evaluator:
  postprocessor:
    _target_: evaluators.evaluator.Postprocessor
    transformations:
      - _target_: conf.conf_utils.partial
        func: numpy.clip
        a_min: 0
        a_max: .inf

dataset:
  config:
    train_samples: 1000000
    memory_mapped: True
