# SPDX-License-Identifier: Apache-2.0
model:
  config:
    n_head: 4
    hidden_size: 128
    dropout: 0.3
    attn_dropout: 0.0
trainer:
  config:
    batch_size: 1024
    num_epochs: 10
    gradient_norm: 1.0
  optimizer:
    lr: .001
