model:
  config:
    n_head: 4
    hidden_size: 192
    dropout: 0.07450385624465683
    quantiles: [0.1, 0.5, 0.9]
    output_selector: 1

dataset:
  config:
    train_samples: 1000000
    MultiID: False
    binarized: True

trainer:
  config:
    batch_size: 1024
    num_epochs: 10
    ema: true
    ema_decay: 0.996038853840747

  optimizer:
    lr: 0.001851534782143349

  criterion:
    _target_: criterion.QuantileLoss
    quantiles: [0.1, 0.5, 0.9]