# SPDX-License-Identifier: MIT
_target_: models.nbeats.NBeatsNet
config:
  stacks:
      - type: "trend"
        num_blocks: 3
        theta_dim: 2
        share_weights: True
        hidden_size: 256
      - type: "seasonality"
        num_blocks: 3
        theta_dim: null
        share_weights: True
        hidden_size: 2048
defaults:
    - _self_
    - /trainer@_global_/trainer: ctltrainer