# SPDX-License-Identifier: Apache-2.0
_target_: models.tft.InterpretableTFT
config:
        quantiles: [ .5 ]
        n_head: 4
        hidden_size: 160
        dropout: 0.1
        attn_dropout: 0.0
        output_selector: 0
defaults:
    - _self_
    - /trainer@_global_/trainer: ctltrainer
