trainer:
  config:
    batch_size: 16384
    ema: False
    num_epochs: 30
  
  optimizer:
    lr: 0.00034901859204728374
  
  criterion:
    _target_: torch.nn.L1Loss

model:
  config:
    stacks:
        - type: "generic"
          num_blocks: 4
          theta_dim: 2
          share_weights: True
          hidden_size: 4096
        - type: "generic"
          num_blocks: 4
          theta_dim: 0
          share_weights: True
          hidden_size: 1024


dataset:
  config:
    memory_mapped: True 
    train_samples: 1000000

evaluator:
  config:
    save_predictions: True
    batch_size: 16384
