name: live_link_vcam
description: A rebuild of the Live Link VCAM app for Flutter, enabling cross-platform deployment.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: "^3.16.3"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  epic_common:
    path: ../../FlutterCommon

  device_info_plus: ^9.1.1
  ffi: ^2.1.0
  logging: ^1.2.0
  ntp: ^2.0.0
  package_info_plus: ^5.0.1
  permission_handler: ^11.1.0
  provider: ^6.1.1
  system_clock: ^2.0.0
  web_socket_channel: ^2.1.0
  streaming_shared_preferences: ^2.0.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  ffigen: ^10.0.0
  pigeon: ^14.0.1
  url_launcher: ^6.2.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Generate localization files
  generate: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: packages/epic_common/assets/fonts/Inter-VariableFont_slnt,wght.ttf

    - family: Droid Sans Mono
      fonts:
        - asset: packages/epic_common/assets/fonts/DroidSansMono.ttf

# Automatically generate arb localization files from a CSV
arb_generator:
  input_filepath: "lib/l10n/l10n.csv"
  output_directory: "lib/l10n"
  filename_prepend: "app_"
  csv_settings:
    description_index: 1
    base_index: 2
