model:
  config:
    stacks:
        - type: "generic"
          num_blocks: 8
          theta_dim: 16
          share_weights: False
          hidden_size: 4096
        - type: "generic"
          num_blocks: 8
          theta_dim: 16
          share_weights: False
          hidden_size: 2048

trainer:
  config:
    ema: True
    ema_decay: 0.9140485910165678
    batch_size: 16384
    num_epochs: 30
  criterion:
    _target_: torch.nn.L1Loss

  optimizer:
    lr: 0.00022462141327530337

dataset:
  config:
    train_samples: 1000000
    MultiID: False
    binarized: True
