model:
  config:
    dropout: 0.27372390753918013
    embedding_dim: 32
    hidden_size: 256
    num_layers: 2
    use_embedding: True

trainer:
  config: 
    ema_decay: 0.9822555327211008
    ema: True
    num_epochs: 5
    batch_size: 128
  optimizer:
    lr: 0.0010081454440377322
  criterion:
    _target_: criterion.GaussianLogLikelihood