hydra:
  sweeper:
    params:
      model.config.stacks.0.type: choice(trend,generic)
      model.config.stacks.1.type: choice(seasonality,generic)
      model.config.stacks.0.num_blocks: choice(2,4,8)
      model.config.stacks.1.num_blocks: choice(2,4,8)
      model.config.stacks.0.theta_dim: choice(2,4,8,16)
      model.config.stacks.1.theta_dim: choice(0,2,4,8,16)
      model.config.stacks.0.share_weights: choice(True,False)
      model.config.stacks.1.share_weights: choice(True,False)
      model.config.stacks.0.hidden_size: choice(256,512,1024,2048,4096)
      model.config.stacks.1.hidden_size: choice(256,512,1024,2048)
      trainer.optimizer.lr: tag(log, interval(1e-5, 1e-2))
      trainer.config.ema: choice(true, false)
      +trainer.config.ema_decay: interval(0.9, 0.9999)
      trainer/criterion: choice(MSE,L1)

dataset:
  config:
    train_samples: 1000000
    MultiID: False
    binarized: True

trainer:
  config:
    batch_size: 16384
    num_epochs: 30